project:
  type: website
  preview: 
    port: 7777

website:
  title: "Rcourse_NSU"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ubogoeva
      - icon: telegram
        href: https://t.me/stats_for_science
    page-footer:
      - icon: table
        # href: https://github.com/quarto-dev/quarto-cli
        # aria-label: Quarto GitHub
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

