---
title: "Список лекций"
author: "Елена Убогоева"
date: '21 February 2023'
categories: lectures
---

На этой странице буду размещать ссылки на презентации после прочитанной лекции.

-   [Презентация](statR_lecture1.qmd) первой лекции (введение в R, векторы)
-   [Презентация](statR_lecture2.qmd) второй лекции (матрицы, списки, датафреймы, условия, циклы)
-   [Презентация](statR_lecture3.qmd) третьей лекции (функциональное программирование в R)
-   [Презентация](statR_lecture4.qmd) четвертой лекции (введение в `tidyverse`)
-   [Презентация](https://polyalineli.github.io/r_plots_guide/rvisualisation.html#1) пятой лекции (прочитала Полина Кисаретова)
-   [Презентация](statR_lecture6.qmd) шестой лекции (описательные статистики, введение в статистику вывода)
-   [Презентация](statR_lecture7.qmd) седьмой лекции (продолжение статистики вывода, тест Стьюдента)
-   [Презентация](statR_lecture8.qmd) восьмой лекции (продолжение теста Стьюдента, мощность тестов, однофакторный дисперсионный анализ)
-   [Презентация](statR_lecture9.qmd) девятой лекции (простая линейная регрессия)
-   [Презентация](statR_lecture10.qmd) десятой лекции (множественная линейная регрессия)
