---
title: "Список тем"
author: "Елена Убогоева"
date: '03 February 2023'
categories: info
---

Предварительный список тем

**Лекция 1: Введение.** История языка, особенности архитектуры. Переменные, векторы, неявное приведение типов. Логические операции, пропущенные значения и способы работы с ними.

**Лекция 2: Основные типы и структуры данных.** Матрицы, списки, датафреймы, их индексация. Установка библиотек. Условные конструкции: `if`, `else`, `ifelse`, `case_when`. Циклы и почему их не рекомендуют использовать. Векторизация как концепт, заменяющий циклы.

**Лекция 3:** Работа с векторами разной длины, ресайклинг. Семейство функций `*apply()`. Создание собственных функций. Импорт и экспорт данных в R. Описательные статистики. Разбор датасета, тайдинг (очистка) данных.

**Лекция 4: Введение в `tidyverse`.** Основные функции пакета `dplyr`, разбор учебного датасета.

**Лекция 5: Введение в `ggplot2` - мощный пакет для визуализации данных.** Философия grammar of graphics. Что такое `aes`, основные геомы.

**Лекция 6: Основы статистического вывода.** Центральная предельная теорема, тест Стьюдента, его непараметрический аналог. Зависимые и независимые выборки. Допущения и ограничения теста Стьюдента

**Лекция 7: Дисперсионный анализ.** Нужен ли однофакторный дисперсионный анализ? Поправка Тьюки. Многофакторный дисперсионный анализ.

**Лекция 8.** Корреляция и линейная регрессия. Хи квадрат и тесты Фишера

**Лекция 9.** Введение в обобщенную линейную модель (GLM). 

**Лекция 10.** Поправки на множественное тестирование.

**Лекция 11.** Биокондактор, пакеты в R специально для решения биологических и биоинформатических задач.

**Лекция 12.** Введение в `quarto`, Rmarkdown (чтобы писать сайты и делать презентации на R).

\
