---
title: 'Анонс курса: "Язык программирования R для анализа данных"'
author: "Елена Убогоева"
date: '03 February 2023'
format: html
editor: visual
categories: news
#theme: flatly
theme: united
---

## Основная информация о курсе

Курс рассчитан на биологов бакалавров (желательно 3-4 курса), магистрантов и любых желающих, кто хочет освоить R для статистической обработки данных и визуализации результатов. Опыт программирования не обязателен, но лишним тоже не будет.

Планируется провести 12 лекций по одной лекции в неделю онлайн на платформе Zoom. Домашние задания и их проверка будут для желающих.

Для регистрации на курс нужно заполнить [гугл форму](https://forms.gle/yjdpR4X9MFJqrwDu5) с небольшой информацией о себе. После регистрации вы будете добавлены в чат в телеграме для удобства координации. Электронная почта нужна, чтобы открывать доступ по почте к материалам курса.

## Предварительный список тем

Можно ознакомиться по [ссылке](list_of_topics.qmd)

## Предварительное расписание занятий

Поскольку желающих много и сложно подобрать оптимальное для всех время, то я могу читать два раза в неделю один и тот же материал, чтобы кто не успел прийти в один день, мог послушать в другой.

**Время:** Первое занятие **19 февраля** в 12.00. Далее расписание: воскресенье 12 утра и четверг в 19 вечера (по времени НСК).\
Планируется делать запись занятий только для участников курса, прошу не распространять дальше.

## По вопросу оплаты

Небольшие донаты по \~100 рублей приветствуются, но не являются обязательными. Кто хочет поддержать, что я делаю - ссылка на оплату будет в телеграм-чате.
